<?php

namespace App\Console\Commands;

use Illuminate\Support\Str;
use Prettus\Repository\Generators\Commands\EntityCommand;
use Symfony\Component\Console\Input\InputOption;

class MakeModuleModelCommand extends EntityCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */

    protected $name = 'make:module-model';


    public function handle()
    {
        $nameModule  = $this->option('module');
        $nameModule = Str::studly($nameModule);
        if ($nameModule) {
            config()->set('repository.generator.basePath', module_path($nameModule));
            config()->set('repository.generator.rootNamespace', "Modules\\$nameModule\\");
        }

        $this->laravel->call([$this, 'fire'], func_get_args());
    }

    public function getOptions()
    {
        $options = parent::getOptions(); // TODO: Change the autogenerated stub

        $options[] = [
            'module',
            null,
            InputOption::VALUE_OPTIONAL,
            'The module attributes.',
            null
        ];

        return $options;
    }
}
