<?php

namespace App\Forms\Components;

use Filament\Forms\Components\Component;
use Illuminate\View\ComponentAttributeBag;

class CustomComponent extends Component
{
    protected string $view = 'forms.components.custom-component';

    public static function make(): static
    {
        return new static();
    }

    public function getDefaultEvaluationParameters(): array
    {
        return parent::getDefaultEvaluationParameters(); // TODO: Change the autogenerated stub
    }

}
